extends:
  - react-app
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
  - prettier

rules:
  # Leave this as a warning while we convert the codebase, then remove it
  '@typescript-eslint/ban-ts-comment': 'warn'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/no-empty-interface': 'warn'
  '@typescript-eslint/no-empty-function': 'warn'
  '@typescript-eslint/no-use-before-define': 'warn'
  '@typescript-eslint/no-non-null-assertion': 'off'
  'no-use-before-define': 'off'

settings:
  react:
    version: detect
