language: node_js
node_js:
  - '8'
script:
  - make init
  - make fmt-check
  - make packages-lint
  - make packages-tslint
  - make packages-test
  - make website-build
  - make storybook-build
  - make examples-build
