swagger: "2.0"
info:
  title: nivo
  version: 1.0.0
  description: nivo API
host: localhost:3000
basePath: /
schemes:
  - http
paths:
  /charts/line:
    post:
      operationId: lineChart
      parameters:
        - name:     props
          in:       body
          required: true
          schema:
            type:       object
            required:
              - width
              - height
              - keys
              - identity
            properties:
              width:
                type: integer
              height:
                type: integer
              keys:
                type:  array
                items:
                  type: string
              identity:
                type: string
      responses:
        200:
          description: line chart

  /charts/bar:
    post:
      operationId: barChart
      parameters:
        - name:     props
          in:       body
          required: true
          schema:
            type:       object
            required:
              - width
              - height
              - keys
              - identity
            properties:
              width:
                type: integer
              height:
                type: integer
              keys:
                type:  array
                items:
                  type: string
              identity:
                type: string
      responses:
        200:
          description: bar chart

  /charts/bubble:
    post:
      operationId: bubbleChart
      parameters:
        - name:     props
          in:       body
          required: true
          schema:
            type:       object
            required:
              - width
              - height
            properties:
              width:
                type: integer
              height:
                type: integer
      responses:
        200:
          description: bubble chart

  /charts/chord:
    post:
      operationId: chordChart
      parameters:
        - name:     props
          in:       body
          required: true
          schema:
            type:       object
            required:
              - width
              - height
              - data
            properties:
              width:
                type: integer
              height:
                type: integer
              data:
                type: string
              padAngle:
                type: number
              innerRadiusRatio:
                type: number
              innerRadiusOffset:
                type: number
              ribbonOpacity:
                type: number
              ribbonBorderWidth:
                type: integer
              arcOpacity:
                type: number
              arcBorderWidth:
                type: integer
              colors:
                type: string
      responses:
        200:
          description: chord diagram