capture:
    baseUrl: http://localhost:3000
    pages:
      - path: /bar
        selector: .chart-tabs__content
        output: ./packages/bar/doc/bar.png

      - path: /bar/canvas
        selector: .chart-tabs__content
        output: ./packages/bar/doc/bar-canvas.png

      - path: /calendar
        selector: .chart-tabs__content
        output: ./packages/calendar/doc/calendar.png

      - path: /chord
        selector: .chart-tabs__content
        output: ./packages/chord/doc/chord.png

      - path: /chord/canvas
        selector: .chart-tabs__content
        output: ./packages/chord/doc/chord-canvas.png

      - path: /bubble
        selector: .chart-tabs__content
        output: ./packages/circle-packing/doc/bubble.png

      - path: /bubble/html
        selector: .chart-tabs__content
        output: ./packages/circle-packing/doc/bubble-html.png

      - path: /bubble/canvas
        selector: .chart-tabs__content
        output: ./packages/circle-packing/doc/bubble-canvas.png

      - path: /bullet
        selector: .chart-tabs__content
        output: ./packages/bullet/doc/bullet.png

      - path: /heatmap
        selector: .chart-tabs__content
        output: ./packages/heatmap/doc/heatmap.png

      - path: /heatmap/canvas
        selector: .chart-tabs__content
        output: ./packages/heatmap/doc/heatmap-canvas.png

      - path: /line
        selector: .chart-tabs__content
        output: ./packages/line/doc/line.png

      - path: /parallel-coordinates
        selector: .chart-tabs__content
        output: ./packages/parallel-coordinates/doc/parallel-coordinates.png

      - path: /parallel-coordinates/canvas
        selector: .chart-tabs__content
        output: ./packages/parallel-coordinates/doc/parallel-coordinates-canvas.png

      - path: /pie
        selector: .chart-tabs__content
        output: ./packages/pie/doc/pie.png

      - path: /radar
        selector: .chart-tabs__content
        output: ./packages/radar/doc/radar.png

      - path: /rose
        selector: .chart-tabs__content
        output: ./packages/rose/doc/rose.png

      - path: /rose/canvas
        selector: .chart-tabs__content
        output: ./packages/rose/doc/rose-canvas.png

      - path: /sankey
        selector: .chart-tabs__content
        output: ./packages/sankey/doc/sankey.png

      - path: /scatterplot
        selector: .chart-tabs__content
        output: ./packages/scatterplot/doc/scatterplot.png

      - path: /scatterplot/canvas
        selector: .chart-tabs__content
        output: ./packages/scatterplot/doc/scatterplot-canvas.png

      - path: /stream
        selector: .chart-tabs__content
        output: ./packages/stream/doc/stream.png

      - path: /sunburst
        selector: .chart-tabs__content
        output: ./packages/sunburst/doc/sunburst.png

      - path: /treemap
        selector: .chart-tabs__content
        output: ./packages/treemap/doc/treemap.png

      - path: /treemap/html
        selector: .chart-tabs__content
        output: ./packages/treemap/doc/treemap-html.png

      - path: /treemap/canvas
        selector: .chart-tabs__content
        output: ./packages/treemap/doc/treemap-canvas.png

      - path: /voronoi
        selector: .chart-tabs__content
        output: ./packages/voronoi/doc/voronoi.png

      - path: /waffle
        selector: .chart-tabs__content
        output: ./packages/waffle/doc/waffle.png

      - path: /waffle/html
        selector: .chart-tabs__content
        output: ./packages/waffle/doc/waffle-html.png

      - path: /waffle/canvas
        selector: .chart-tabs__content
        output: ./packages/waffle/doc/waffle-canvas.png
