capture:
    baseUrl: http://localhost:3000
    pages:
      # capture illustrations for readme
      - path: /geomap
        selector: .chart-tabs__content
        output: ./packages/geo/doc/geomap.png
    
      - path: /geomap/canvas
        selector: .chart-tabs__content
        output: ./packages/geo/doc/geomap-canvas.png

      - path: /choropleth
        selector: .chart-tabs__content
        output: ./packages/geo/doc/choropleth.png
    
      - path: /choropleth/canvas
        selector: .chart-tabs__content
        output: ./packages/geo/doc/choropleth-canvas.png

      - path: /bar
        selector: .chart-tabs__content
        output: ./packages/bar/doc/bar.png

      - path: /bar/canvas
        selector: .chart-tabs__content
        output: ./packages/bar/doc/bar-canvas.png

      - path: /calendar
        selector: .chart-tabs__content
        output: ./packages/calendar/doc/calendar.png

      - path: /chord
        selector: .chart-tabs__content
        output: ./packages/chord/doc/chord.png

      - path: /chord/canvas
        selector: .chart-tabs__content
        output: ./packages/chord/doc/chord-canvas.png

      - path: /bubble
        selector: .chart-tabs__content
        output: ./packages/circle-packing/doc/bubble.png

      - path: /bubble/html
        selector: .chart-tabs__content
        output: ./packages/circle-packing/doc/bubble-html.png

      - path: /bubble/canvas
        selector: .chart-tabs__content
        output: ./packages/circle-packing/doc/bubble-canvas.png

      - path: /bullet
        selector: .chart-tabs__content
        output: ./packages/bullet/doc/bullet.png

      - path: /heatmap
        selector: .chart-tabs__content
        output: ./packages/heatmap/doc/heatmap.png

      - path: /heatmap/canvas
        selector: .chart-tabs__content
        output: ./packages/heatmap/doc/heatmap-canvas.png

      - path: /line
        selector: .chart-tabs__content
        output: ./packages/line/doc/line.png

      - path: /parallel-coordinates
        selector: .chart-tabs__content
        output: ./packages/parallel-coordinates/doc/parallel-coordinates.png

      - path: /parallel-coordinates/canvas
        selector: .chart-tabs__content
        output: ./packages/parallel-coordinates/doc/parallel-coordinates-canvas.png

      - path: /pie
        selector: .chart-tabs__content
        output: ./packages/pie/doc/pie.png

      - path: /radar
        selector: .chart-tabs__content
        output: ./packages/radar/doc/radar.png

      - path: /sankey
        selector: .chart-tabs__content
        output: ./packages/sankey/doc/sankey.png

      - path: /scatterplot
        selector: .chart-tabs__content
        output: ./packages/scatterplot/doc/scatterplot.png

      - path: /scatterplot/canvas
        selector: .chart-tabs__content
        output: ./packages/scatterplot/doc/scatterplot-canvas.png

      - path: /stream
        selector: .chart-tabs__content
        output: ./packages/stream/doc/stream.png

      - path: /sunburst
        selector: .chart-tabs__content
        output: ./packages/sunburst/doc/sunburst.png

      - path: /treemap
        selector: .chart-tabs__content
        output: ./packages/treemap/doc/treemap.png

      - path: /treemap/html
        selector: .chart-tabs__content
        output: ./packages/treemap/doc/treemap-html.png

      - path: /treemap/canvas
        selector: .chart-tabs__content
        output: ./packages/treemap/doc/treemap-canvas.png

      - path: /voronoi
        selector: .chart-tabs__content
        output: ./packages/voronoi/doc/voronoi.png

      - path: /waffle
        selector: .chart-tabs__content
        output: ./packages/waffle/doc/waffle.png

      - path: /waffle/html
        selector: .chart-tabs__content
        output: ./packages/waffle/doc/waffle-html.png

      - path: /waffle/canvas
        selector: .chart-tabs__content
        output: ./packages/waffle/doc/waffle-canvas.png

      # capture icons for website
      - path: /icons
        selector: '#bar-grey'
        output: ./website/src/assets/icons/bar-grey.png

      - path: /icons
        selector: '#bar-red'
        output: ./website/src/assets/icons/bar-red.png
    
      - path: /icons
        selector: '#heatmap-grey'
        output: ./website/src/assets/icons/heatmap-grey.png

      - path: /icons
        selector: '#heatmap-red'
        output: ./website/src/assets/icons/heatmap-red.png

      - path: /icons
        selector: '#waffle-grey'
        output: ./website/src/assets/icons/waffle-grey.png

      - path: /icons
        selector: '#waffle-red'
        output: ./website/src/assets/icons/waffle-red.png

      - path: /icons
        selector: '#pie-grey'
        output: ./website/src/assets/icons/pie-grey.png

      - path: /icons
        selector: '#pie-red'
        output: ./website/src/assets/icons/pie-red.png
      
      #- path: /icons
      #  selector: '#radar-grey'
      #  output: ./website/src/assets/icons/radar-grey.png

      #- path: /icons
      #  selector: '#radar-red'
      #  output: ./website/src/assets/icons/radar-red.png

      - path: /icons
        selector: '#line-grey'
        output: ./website/src/assets/icons/line-grey.png

      - path: /icons
        selector: '#line-red'
        output: ./website/src/assets/icons/line-red.png

      - path: /icons
        selector: '#bullet-grey'
        output: ./website/src/assets/icons/bullet-grey.png

      - path: /icons
        selector: '#bullet-red'
        output: ./website/src/assets/icons/bullet-red.png
      
      - path: /icons
        selector: '#circle-packing-grey'
        output: ./website/src/assets/icons/circle-packing-grey.png

      - path: /icons
        selector: '#circle-packing-red'
        output: ./website/src/assets/icons/circle-packing-red.png 

      - path: /icons
        selector: '#stream-grey'
        output: ./website/src/assets/icons/stream-grey.png

      - path: /icons
        selector: '#stream-red'
        output: ./website/src/assets/icons/stream-red.png

      - path: /icons
        selector: '#scatterplot-grey'
        output: ./website/src/assets/icons/scatterplot-grey.png

      - path: /icons
        selector: '#scatterplot-red'
        output: ./website/src/assets/icons/scatterplot-red.png
  
      - path: /icons
        selector: '#parallel-coordinates-grey'
        output: ./website/src/assets/icons/parallel-coordinates-grey.png

      - path: /icons
        selector: '#parallel-coordinates-red'
        output: ./website/src/assets/icons/parallel-coordinates-red.png

      - path: /icons
        selector: '#geomap-grey'
        output: ./website/src/assets/icons/geomap-grey.png

      - path: /icons
        selector: '#geomap-red'
        output: ./website/src/assets/icons/geomap-red.png

      - path: /icons
        selector: '#choropleth-grey'
        output: ./website/src/assets/icons/choropleth-grey.png

      - path: /icons
        selector: '#choropleth-red'
        output: ./website/src/assets/icons/choropleth-red.png
