parser: babel-eslint

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true

env:
  browser: true

globals:
  global: true

extends:
  - eslint:recommended
  - plugin:react/recommended

rules:
  react/jsx-key: 0