import type { Metadata } from "next";
import "./globals.css";
/*
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    // <body className={`${geistSans.variable} ${geistMono.variable}`}>
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
